output:
  type: "csv"
  dir: "./"
  filename: "exemple_filename"

datasets:
  dataset1:
    audio_dir: "resources/common_voice_05/wav"
    reference_dir: "resources/common_voice_05/txt"

providers:
  faster_whisper:
    provider: "faster_whisper"
    model: "medium"
    compute_type: "int8"
    device: "cpu"
    beam_size: 5
    language: "pt"
  whisper_1:
    provider: "whisper"
    model: "medium"
    device: "cpu"
    language: "pt"
    fp16: False
  whisper_2:
    provider: "whisper"
    model: "large-v3-turbo"
    device: "cpu"
    language: "pt"
    fp16: False
  wav2vec:
    provider: "wav2vec"
    model: "facebook/wav2vec2-large-xlsr-53-portuguese"
    compute_type: "float32"
    device: "cpu"
    language: "pt"
  hf:
    provider: "hf"
    model: "facebook/wav2vec2-large-xlsr-53-portuguese"
    compute_type: "float32"
    device: "cpu"
    language: "pt"
