[tool.poetry]
name = "tcc-benchmark"
version = "0.1.0"
description = ""
authors = ["BDu4rTe <brianschierduarte@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
jiwer = "^3.0.4"
faster-whisper = "^1.0.3"
pytube = "^15.0.0"
pydub = "^0.25.1"
pytubefix = "^6.16.2"
vosk = "^0.3.45"
llvmlite = "^0.43.0"
numba = "^0.60.0"
openai-whisper = "^20231117"
transformers = "^4.44.2"
librosa = "^0.10.2.post1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
